//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camposSemanticos.ServicioLematizacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reconocimiento", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class Reconocimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormaCanonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFlexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFormaCanonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private camposSemanticos.ServicioLematizacion.InfoCanonica InfoCanonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PronombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonica {
            get {
                return this.FormaCanonicaField;
            }
            set {
                if ((object.ReferenceEquals(this.FormaCanonicaField, value) != true)) {
                    this.FormaCanonicaField = value;
                    this.RaisePropertyChanged("FormaCanonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia {
            get {
                return this.FrecuenciaField;
            }
            set {
                if ((this.FrecuenciaField.Equals(value) != true)) {
                    this.FrecuenciaField = value;
                    this.RaisePropertyChanged("Frecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion {
            get {
                return this.IdFlexionField;
            }
            set {
                if ((this.IdFlexionField.Equals(value) != true)) {
                    this.IdFlexionField = value;
                    this.RaisePropertyChanged("IdFlexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica {
            get {
                return this.IdFormaCanonicaField;
            }
            set {
                if ((this.IdFormaCanonicaField.Equals(value) != true)) {
                    this.IdFormaCanonicaField = value;
                    this.RaisePropertyChanged("IdFormaCanonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public camposSemanticos.ServicioLematizacion.InfoCanonica InfoCanonica {
            get {
                return this.InfoCanonicaField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoCanonicaField, value) != true)) {
                    this.InfoCanonicaField = value;
                    this.RaisePropertyChanged("InfoCanonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra {
            get {
                return this.PalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabraField, value) != true)) {
                    this.PalabraField = value;
                    this.RaisePropertyChanged("Palabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijos {
            get {
                return this.PrefijosField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijosField, value) != true)) {
                    this.PrefijosField = value;
                    this.RaisePropertyChanged("Prefijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pronombres {
            get {
                return this.PronombresField;
            }
            set {
                if ((object.ReferenceEquals(this.PronombresField, value) != true)) {
                    this.PronombresField = value;
                    this.RaisePropertyChanged("Pronombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCanonica", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoCanonica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AntiguaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DRAEXXIIIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormaCanonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaGNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCategoriaLKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFlexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxAcepcionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxEtimologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumAcepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumAcepcionSecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumEtimologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosAcepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosAcepcionSecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Antigua {
            get {
                return this.AntiguaField;
            }
            set {
                if ((this.AntiguaField.Equals(value) != true)) {
                    this.AntiguaField = value;
                    this.RaisePropertyChanged("Antigua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DRAEXXIII {
            get {
                return this.DRAEXXIIIField;
            }
            set {
                if ((this.DRAEXXIIIField.Equals(value) != true)) {
                    this.DRAEXXIIIField = value;
                    this.RaisePropertyChanged("DRAEXXIII");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonica {
            get {
                return this.FormaCanonicaField;
            }
            set {
                if ((object.ReferenceEquals(this.FormaCanonicaField, value) != true)) {
                    this.FormaCanonicaField = value;
                    this.RaisePropertyChanged("FormaCanonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia {
            get {
                return this.FrecuenciaField;
            }
            set {
                if ((this.FrecuenciaField.Equals(value) != true)) {
                    this.FrecuenciaField = value;
                    this.RaisePropertyChanged("Frecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaGN {
            get {
                return this.IdCategoriaGNField;
            }
            set {
                if ((this.IdCategoriaGNField.Equals(value) != true)) {
                    this.IdCategoriaGNField = value;
                    this.RaisePropertyChanged("IdCategoriaGN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCategoriaLK {
            get {
                return this.IdCategoriaLKField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCategoriaLKField, value) != true)) {
                    this.IdCategoriaLKField = value;
                    this.RaisePropertyChanged("IdCategoriaLK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion {
            get {
                return this.IdFlexionField;
            }
            set {
                if ((this.IdFlexionField.Equals(value) != true)) {
                    this.IdFlexionField = value;
                    this.RaisePropertyChanged("IdFlexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxAcepciones {
            get {
                return this.MaxAcepcionesField;
            }
            set {
                if ((this.MaxAcepcionesField.Equals(value) != true)) {
                    this.MaxAcepcionesField = value;
                    this.RaisePropertyChanged("MaxAcepciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxEtimologia {
            get {
                return this.MaxEtimologiaField;
            }
            set {
                if ((this.MaxEtimologiaField.Equals(value) != true)) {
                    this.MaxEtimologiaField = value;
                    this.RaisePropertyChanged("MaxEtimologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumAcepcion {
            get {
                return this.NumAcepcionField;
            }
            set {
                if ((this.NumAcepcionField.Equals(value) != true)) {
                    this.NumAcepcionField = value;
                    this.RaisePropertyChanged("NumAcepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumAcepcionSec {
            get {
                return this.NumAcepcionSecField;
            }
            set {
                if ((this.NumAcepcionSecField.Equals(value) != true)) {
                    this.NumAcepcionSecField = value;
                    this.RaisePropertyChanged("NumAcepcionSec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEtimologia {
            get {
                return this.NumEtimologiaField;
            }
            set {
                if ((this.NumEtimologiaField.Equals(value) != true)) {
                    this.NumEtimologiaField = value;
                    this.RaisePropertyChanged("NumEtimologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosAcepcion {
            get {
                return this.PosAcepcionField;
            }
            set {
                if ((this.PosAcepcionField.Equals(value) != true)) {
                    this.PosAcepcionField = value;
                    this.RaisePropertyChanged("PosAcepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosAcepcionSec {
            get {
                return this.PosAcepcionSecField;
            }
            set {
                if ((this.PosAcepcionSecField.Equals(value) != true)) {
                    this.PosAcepcionSecField = value;
                    this.RaisePropertyChanged("PosAcepcionSec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamtextFrase", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class ParamtextFrase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextPalabra> PalabrasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frase {
            get {
                return this.FraseField;
            }
            set {
                if ((object.ReferenceEquals(this.FraseField, value) != true)) {
                    this.FraseField = value;
                    this.RaisePropertyChanged("Frase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextPalabra> Palabras {
            get {
                return this.PalabrasField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabrasField, value) != true)) {
                    this.PalabrasField = value;
                    this.RaisePropertyChanged("Palabras");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamtextPalabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class ParamtextPalabra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormaCanonicaLKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCategoriaLKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdParrafoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> InfoMorfoMatchingLKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> InformacionMorfologicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalabraLKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosMarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonicaLK {
            get {
                return this.FormaCanonicaLKField;
            }
            set {
                if ((object.ReferenceEquals(this.FormaCanonicaLKField, value) != true)) {
                    this.FormaCanonicaLKField = value;
                    this.RaisePropertyChanged("FormaCanonicaLK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCategoriaLK {
            get {
                return this.IdCategoriaLKField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCategoriaLKField, value) != true)) {
                    this.IdCategoriaLKField = value;
                    this.RaisePropertyChanged("IdCategoriaLK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFrase {
            get {
                return this.IdFraseField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFraseField, value) != true)) {
                    this.IdFraseField = value;
                    this.RaisePropertyChanged("IdFrase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdParrafo {
            get {
                return this.IdParrafoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdParrafoField, value) != true)) {
                    this.IdParrafoField = value;
                    this.RaisePropertyChanged("IdParrafo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> InfoMorfoMatchingLK {
            get {
                return this.InfoMorfoMatchingLKField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMorfoMatchingLKField, value) != true)) {
                    this.InfoMorfoMatchingLKField = value;
                    this.RaisePropertyChanged("InfoMorfoMatchingLK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> InformacionMorfologica {
            get {
                return this.InformacionMorfologicaField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacionMorfologicaField, value) != true)) {
                    this.InformacionMorfologicaField = value;
                    this.RaisePropertyChanged("InformacionMorfologica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra {
            get {
                return this.PalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabraField, value) != true)) {
                    this.PalabraField = value;
                    this.RaisePropertyChanged("Palabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalabraLK {
            get {
                return this.PalabraLKField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabraLKField, value) != true)) {
                    this.PalabraLKField = value;
                    this.RaisePropertyChanged("PalabraLK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosMark {
            get {
                return this.PosMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.PosMarkField, value) != true)) {
                    this.PosMarkField = value;
                    this.RaisePropertyChanged("PosMark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoUnaFrase", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoUnaFrase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FraseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaPalabra> PalabrasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frase {
            get {
                return this.FraseField;
            }
            set {
                if ((object.ReferenceEquals(this.FraseField, value) != true)) {
                    this.FraseField = value;
                    this.RaisePropertyChanged("Frase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaPalabra> Palabras {
            get {
                return this.PalabrasField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabrasField, value) != true)) {
                    this.PalabrasField = value;
                    this.RaisePropertyChanged("Palabras");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoUnaPalabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoUnaPalabra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormaCanonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFlexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFormaCanonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PronombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaCanonica {
            get {
                return this.FormaCanonicaField;
            }
            set {
                if ((object.ReferenceEquals(this.FormaCanonicaField, value) != true)) {
                    this.FormaCanonicaField = value;
                    this.RaisePropertyChanged("FormaCanonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia {
            get {
                return this.FrecuenciaField;
            }
            set {
                if ((this.FrecuenciaField.Equals(value) != true)) {
                    this.FrecuenciaField = value;
                    this.RaisePropertyChanged("Frecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion {
            get {
                return this.IdFlexionField;
            }
            set {
                if ((this.IdFlexionField.Equals(value) != true)) {
                    this.IdFlexionField = value;
                    this.RaisePropertyChanged("IdFlexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica {
            get {
                return this.IdFormaCanonicaField;
            }
            set {
                if ((this.IdFormaCanonicaField.Equals(value) != true)) {
                    this.IdFormaCanonicaField = value;
                    this.RaisePropertyChanged("IdFormaCanonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra {
            get {
                return this.PalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabraField, value) != true)) {
                    this.PalabraField = value;
                    this.RaisePropertyChanged("Palabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosMark {
            get {
                return this.PosMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.PosMarkField, value) != true)) {
                    this.PosMarkField = value;
                    this.RaisePropertyChanged("PosMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((this.PosicionField.Equals(value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijos {
            get {
                return this.PrefijosField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijosField, value) != true)) {
                    this.PrefijosField = value;
                    this.RaisePropertyChanged("Prefijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pronombres {
            get {
                return this.PronombresField;
            }
            set {
                if ((object.ReferenceEquals(this.PronombresField, value) != true)) {
                    this.PronombresField = value;
                    this.RaisePropertyChanged("Pronombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPalabra", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoPalabra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFlexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFormaCanonicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia {
            get {
                return this.FrecuenciaField;
            }
            set {
                if ((this.FrecuenciaField.Equals(value) != true)) {
                    this.FrecuenciaField = value;
                    this.RaisePropertyChanged("Frecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion {
            get {
                return this.IdFlexionField;
            }
            set {
                if ((this.IdFlexionField.Equals(value) != true)) {
                    this.IdFlexionField = value;
                    this.RaisePropertyChanged("IdFlexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica {
            get {
                return this.IdFormaCanonicaField;
            }
            set {
                if ((this.IdFormaCanonicaField.Equals(value) != true)) {
                    this.IdFormaCanonicaField = value;
                    this.RaisePropertyChanged("IdFormaCanonica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFlexionador", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoFlexionador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFlexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalabraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion {
            get {
                return this.IdFlexionField;
            }
            set {
                if ((this.IdFlexionField.Equals(value) != true)) {
                    this.IdFlexionField = value;
                    this.RaisePropertyChanged("IdFlexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Palabra {
            get {
                return this.PalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.PalabraField, value) != true)) {
                    this.PalabraField = value;
                    this.RaisePropertyChanged("Palabra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVerbo", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoVerbo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrecuenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFlexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFormaCanonicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfinitivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Frecuencia {
            get {
                return this.FrecuenciaField;
            }
            set {
                if ((this.FrecuenciaField.Equals(value) != true)) {
                    this.FrecuenciaField = value;
                    this.RaisePropertyChanged("Frecuencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFlexion {
            get {
                return this.IdFlexionField;
            }
            set {
                if ((this.IdFlexionField.Equals(value) != true)) {
                    this.IdFlexionField = value;
                    this.RaisePropertyChanged("IdFlexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaCanonica {
            get {
                return this.IdFormaCanonicaField;
            }
            set {
                if ((this.IdFormaCanonicaField.Equals(value) != true)) {
                    this.IdFormaCanonicaField = value;
                    this.RaisePropertyChanged("IdFormaCanonica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Infinitivo {
            get {
                return this.InfinitivoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfinitivoField, value) != true)) {
                    this.InfinitivoField = value;
                    this.RaisePropertyChanged("Infinitivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPrimitiva", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoPrimitiva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFamiliaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSufijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReglaPrefijalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReglaSufijalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SufijoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaPadre {
            get {
                return this.IdCategoriaPadreField;
            }
            set {
                if ((this.IdCategoriaPadreField.Equals(value) != true)) {
                    this.IdCategoriaPadreField = value;
                    this.RaisePropertyChanged("IdCategoriaPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFamilia {
            get {
                return this.IdFamiliaField;
            }
            set {
                if ((this.IdFamiliaField.Equals(value) != true)) {
                    this.IdFamiliaField = value;
                    this.RaisePropertyChanged("IdFamilia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrefijo {
            get {
                return this.IdPrefijoField;
            }
            set {
                if ((this.IdPrefijoField.Equals(value) != true)) {
                    this.IdPrefijoField = value;
                    this.RaisePropertyChanged("IdPrefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSufijo {
            get {
                return this.IdSufijoField;
            }
            set {
                if ((this.IdSufijoField.Equals(value) != true)) {
                    this.IdSufijoField = value;
                    this.RaisePropertyChanged("IdSufijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Padre {
            get {
                return this.PadreField;
            }
            set {
                if ((object.ReferenceEquals(this.PadreField, value) != true)) {
                    this.PadreField = value;
                    this.RaisePropertyChanged("Padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReglaPrefijal {
            get {
                return this.ReglaPrefijalField;
            }
            set {
                if ((this.ReglaPrefijalField.Equals(value) != true)) {
                    this.ReglaPrefijalField = value;
                    this.RaisePropertyChanged("ReglaPrefijal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReglaSufijal {
            get {
                return this.ReglaSufijalField;
            }
            set {
                if ((this.ReglaSufijalField.Equals(value) != true)) {
                    this.ReglaSufijalField = value;
                    this.RaisePropertyChanged("ReglaSufijal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sufijo {
            get {
                return this.SufijoField;
            }
            set {
                if ((object.ReferenceEquals(this.SufijoField, value) != true)) {
                    this.SufijoField = value;
                    this.RaisePropertyChanged("Sufijo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPrefijo", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoPrefijo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CorteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtimologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoCanonicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SilabacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Corte {
            get {
                return this.CorteField;
            }
            set {
                if ((this.CorteField.Equals(value) != true)) {
                    this.CorteField = value;
                    this.RaisePropertyChanged("Corte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etimologia {
            get {
                return this.EtimologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.EtimologiaField, value) != true)) {
                    this.EtimologiaField = value;
                    this.RaisePropertyChanged("Etimologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrefijoCanonico {
            get {
                return this.PrefijoCanonicoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoCanonicoField, value) != true)) {
                    this.PrefijoCanonicoField = value;
                    this.RaisePropertyChanged("PrefijoCanonico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Significado {
            get {
                return this.SignificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.SignificadoField, value) != true)) {
                    this.SignificadoField = value;
                    this.RaisePropertyChanged("Significado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Silabacion {
            get {
                return this.SilabacionField;
            }
            set {
                if ((object.ReferenceEquals(this.SilabacionField, value) != true)) {
                    this.SilabacionField = value;
                    this.RaisePropertyChanged("Silabacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPrefijo {
            get {
                return this.TipoPrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPrefijoField, value) != true)) {
                    this.TipoPrefijoField = value;
                    this.RaisePropertyChanged("TipoPrefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variantes {
            get {
                return this.VariantesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantesField, value) != true)) {
                    this.VariantesField = value;
                    this.RaisePropertyChanged("Variantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFlexion", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoFlexion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlexionAbrevEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlexionAbrevEsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlexionEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlexionEsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionAbrevEn {
            get {
                return this.FlexionAbrevEnField;
            }
            set {
                if ((object.ReferenceEquals(this.FlexionAbrevEnField, value) != true)) {
                    this.FlexionAbrevEnField = value;
                    this.RaisePropertyChanged("FlexionAbrevEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionAbrevEs {
            get {
                return this.FlexionAbrevEsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlexionAbrevEsField, value) != true)) {
                    this.FlexionAbrevEsField = value;
                    this.RaisePropertyChanged("FlexionAbrevEs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionEn {
            get {
                return this.FlexionEnField;
            }
            set {
                if ((object.ReferenceEquals(this.FlexionEnField, value) != true)) {
                    this.FlexionEnField = value;
                    this.RaisePropertyChanged("FlexionEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlexionEs {
            get {
                return this.FlexionEsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlexionEsField, value) != true)) {
                    this.FlexionEsField = value;
                    this.RaisePropertyChanged("FlexionEs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCategoria", Namespace="http://schemas.datacontract.org/2004/07/ServicioLematizacionWCF")]
    [System.SerializableAttribute()]
    public partial class InfoCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaAbrevEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaAbrevEsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaEsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaAbrevEn {
            get {
                return this.CategoriaAbrevEnField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaAbrevEnField, value) != true)) {
                    this.CategoriaAbrevEnField = value;
                    this.RaisePropertyChanged("CategoriaAbrevEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaAbrevEs {
            get {
                return this.CategoriaAbrevEsField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaAbrevEsField, value) != true)) {
                    this.CategoriaAbrevEsField = value;
                    this.RaisePropertyChanged("CategoriaAbrevEs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaEn {
            get {
                return this.CategoriaEnField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaEnField, value) != true)) {
                    this.CategoriaEnField = value;
                    this.RaisePropertyChanged("CategoriaEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaEs {
            get {
                return this.CategoriaEsField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaEsField, value) != true)) {
                    this.CategoriaEsField = value;
                    this.RaisePropertyChanged("CategoriaEs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLematizacion.IServicioLematizacion")]
    public interface IServicioLematizacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/EsVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/EsVerboResponse")]
        bool EsVerbo(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/EsVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/EsVerboResponse")]
        System.Threading.Tasks.Task<bool> EsVerboAsync(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/Reconocer", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> Reconocer(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/Reconocer", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento>> ReconocerAsync(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrases", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrasesResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> ReconocerTextoPorFrases(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrases", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerTextoPorFrasesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase>> ReconocerTextoPorFrasesAsync(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerLinguakit", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerLinguakitResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> ReconocerLinguakit(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerLinguakit", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerLinguakitResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase>> ReconocerLinguakitAsync(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerFrases", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerFrasesResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase> ReconocerFrases(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerFrases", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerFrasesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase>> ReconocerFrasesAsync(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase> frases, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerFlexible", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerFlexibleResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> ReconocerFlexible(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerFlexible", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerFlexibleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento>> ReconocerFlexibleAsync(string palabra, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerVerboResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> ReconocerVerbo(string verbo, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ReconocerVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ReconocerVerboResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento>> ReconocerVerboAsync(string verbo, string idioma, bool multiPref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCanonica", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCanonicaResponse")]
        camposSemanticos.ServicioLematizacion.InfoCanonica ConsultaCanonica(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCanonica", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCanonicaResponse")]
        System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoCanonica> ConsultaCanonicaAsync(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPalabra", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPalabraResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPalabra> ConsultaPalabra(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPalabra", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPalabraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPalabra>> ConsultaPalabraAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradas", ReplyAction="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradasResponse")]
        System.Collections.Generic.List<string> PalabrasNoEncontradas(System.Collections.Generic.List<string> listaPalabras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradas", ReplyAction="http://tempuri.org/IServicioLematizacion/PalabrasNoEncontradasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> PalabrasNoEncontradasAsync(System.Collections.Generic.List<string> listaPalabras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexionador", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionadorResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoFlexionador> ConsultaFlexionador(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexionador", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionadorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoFlexionador>> ConsultaFlexionadorAsync(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaVerboResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoVerbo> ConsultaVerbo(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaVerbo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaVerboResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoVerbo>> ConsultaVerboAsync(string verbo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrimitiva", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrimitivaResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrimitiva> ConsultaPrimitiva(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrimitiva", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrimitivaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrimitiva>> ConsultaPrimitivaAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrefijo> ConsultaPrefijo(string prefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijo", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrefijo>> ConsultaPrefijoAsync(string prefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCod", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCodResponse")]
        camposSemanticos.ServicioLematizacion.InfoPrefijo ConsultaPrefijoCod(int idPrefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCod", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaPrefijoCodResponse")]
        System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoPrefijo> ConsultaPrefijoCodAsync(int idPrefijo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexion", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionResponse")]
        camposSemanticos.ServicioLematizacion.InfoFlexion ConsultaFlexion(int idFlexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaFlexion", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaFlexionResponse")]
        System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoFlexion> ConsultaFlexionAsync(int idFlexion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCategoria", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCategoriaResponse")]
        camposSemanticos.ServicioLematizacion.InfoCategoria ConsultaCategoria(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCategoria", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCategoriaResponse")]
        System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoCategoria> ConsultaCategoriaAsync(int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexiones", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexionesResponse")]
        System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoFlexion> ConsultaCodigosFlexiones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexiones", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosFlexionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoFlexion>> ConsultaCodigosFlexionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategorias", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategoriasResponse")]
        System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoCategoria> ConsultaCodigosCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategorias", ReplyAction="http://tempuri.org/IServicioLematizacion/ConsultaCodigosCategoriasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoCategoria>> ConsultaCodigosCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/PosTaggerTip", ReplyAction="http://tempuri.org/IServicioLematizacion/PosTaggerTipResponse")]
        System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, System.Collections.Generic.KeyValuePair<string, string>>>> PosTaggerTip(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLematizacion/PosTaggerTip", ReplyAction="http://tempuri.org/IServicioLematizacion/PosTaggerTipResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, System.Collections.Generic.KeyValuePair<string, string>>>>> PosTaggerTipAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLematizacionChannel : camposSemanticos.ServicioLematizacion.IServicioLematizacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLematizacionClient : System.ServiceModel.ClientBase<camposSemanticos.ServicioLematizacion.IServicioLematizacion>, camposSemanticos.ServicioLematizacion.IServicioLematizacion {
        
        public ServicioLematizacionClient() {
        }
        
        public ServicioLematizacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLematizacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLematizacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLematizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EsVerbo(string verbo) {
            return base.Channel.EsVerbo(verbo);
        }
        
        public System.Threading.Tasks.Task<bool> EsVerboAsync(string verbo) {
            return base.Channel.EsVerboAsync(verbo);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> Reconocer(string palabra, string idioma, bool multiPref) {
            return base.Channel.Reconocer(palabra, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento>> ReconocerAsync(string palabra, string idioma, bool multiPref) {
            return base.Channel.ReconocerAsync(palabra, idioma, multiPref);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> ReconocerTextoPorFrases(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref) {
            return base.Channel.ReconocerTextoPorFrases(frases, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase>> ReconocerTextoPorFrasesAsync(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref) {
            return base.Channel.ReconocerTextoPorFrasesAsync(frases, idioma, multiPref);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> ReconocerLinguakit(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref) {
            return base.Channel.ReconocerLinguakit(frases, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase>> ReconocerLinguakitAsync(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.ParamtextFrase> frases, string idioma, bool multiPref) {
            return base.Channel.ReconocerLinguakitAsync(frases, idioma, multiPref);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase> ReconocerFrases(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase> frases, string idioma, bool multiPref) {
            return base.Channel.ReconocerFrases(frases, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase>> ReconocerFrasesAsync(System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoUnaFrase> frases, string idioma, bool multiPref) {
            return base.Channel.ReconocerFrasesAsync(frases, idioma, multiPref);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> ReconocerFlexible(string palabra, string idioma, bool multiPref) {
            return base.Channel.ReconocerFlexible(palabra, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento>> ReconocerFlexibleAsync(string palabra, string idioma, bool multiPref) {
            return base.Channel.ReconocerFlexibleAsync(palabra, idioma, multiPref);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento> ReconocerVerbo(string verbo, string idioma, bool multiPref) {
            return base.Channel.ReconocerVerbo(verbo, idioma, multiPref);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.Reconocimiento>> ReconocerVerboAsync(string verbo, string idioma, bool multiPref) {
            return base.Channel.ReconocerVerboAsync(verbo, idioma, multiPref);
        }
        
        public camposSemanticos.ServicioLematizacion.InfoCanonica ConsultaCanonica(int idFormaCanonica) {
            return base.Channel.ConsultaCanonica(idFormaCanonica);
        }
        
        public System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoCanonica> ConsultaCanonicaAsync(int idFormaCanonica) {
            return base.Channel.ConsultaCanonicaAsync(idFormaCanonica);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPalabra> ConsultaPalabra(string palabra) {
            return base.Channel.ConsultaPalabra(palabra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPalabra>> ConsultaPalabraAsync(string palabra) {
            return base.Channel.ConsultaPalabraAsync(palabra);
        }
        
        public System.Collections.Generic.List<string> PalabrasNoEncontradas(System.Collections.Generic.List<string> listaPalabras) {
            return base.Channel.PalabrasNoEncontradas(listaPalabras);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> PalabrasNoEncontradasAsync(System.Collections.Generic.List<string> listaPalabras) {
            return base.Channel.PalabrasNoEncontradasAsync(listaPalabras);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoFlexionador> ConsultaFlexionador(int idFormaCanonica) {
            return base.Channel.ConsultaFlexionador(idFormaCanonica);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoFlexionador>> ConsultaFlexionadorAsync(int idFormaCanonica) {
            return base.Channel.ConsultaFlexionadorAsync(idFormaCanonica);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoVerbo> ConsultaVerbo(string verbo) {
            return base.Channel.ConsultaVerbo(verbo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoVerbo>> ConsultaVerboAsync(string verbo) {
            return base.Channel.ConsultaVerboAsync(verbo);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrimitiva> ConsultaPrimitiva(string palabra) {
            return base.Channel.ConsultaPrimitiva(palabra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrimitiva>> ConsultaPrimitivaAsync(string palabra) {
            return base.Channel.ConsultaPrimitivaAsync(palabra);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrefijo> ConsultaPrefijo(string prefijo) {
            return base.Channel.ConsultaPrefijo(prefijo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioLematizacion.InfoPrefijo>> ConsultaPrefijoAsync(string prefijo) {
            return base.Channel.ConsultaPrefijoAsync(prefijo);
        }
        
        public camposSemanticos.ServicioLematizacion.InfoPrefijo ConsultaPrefijoCod(int idPrefijo) {
            return base.Channel.ConsultaPrefijoCod(idPrefijo);
        }
        
        public System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoPrefijo> ConsultaPrefijoCodAsync(int idPrefijo) {
            return base.Channel.ConsultaPrefijoCodAsync(idPrefijo);
        }
        
        public camposSemanticos.ServicioLematizacion.InfoFlexion ConsultaFlexion(int idFlexion) {
            return base.Channel.ConsultaFlexion(idFlexion);
        }
        
        public System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoFlexion> ConsultaFlexionAsync(int idFlexion) {
            return base.Channel.ConsultaFlexionAsync(idFlexion);
        }
        
        public camposSemanticos.ServicioLematizacion.InfoCategoria ConsultaCategoria(int idCategoria) {
            return base.Channel.ConsultaCategoria(idCategoria);
        }
        
        public System.Threading.Tasks.Task<camposSemanticos.ServicioLematizacion.InfoCategoria> ConsultaCategoriaAsync(int idCategoria) {
            return base.Channel.ConsultaCategoriaAsync(idCategoria);
        }
        
        public System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoFlexion> ConsultaCodigosFlexiones() {
            return base.Channel.ConsultaCodigosFlexiones();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoFlexion>> ConsultaCodigosFlexionesAsync() {
            return base.Channel.ConsultaCodigosFlexionesAsync();
        }
        
        public System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoCategoria> ConsultaCodigosCategorias() {
            return base.Channel.ConsultaCodigosCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, camposSemanticos.ServicioLematizacion.InfoCategoria>> ConsultaCodigosCategoriasAsync() {
            return base.Channel.ConsultaCodigosCategoriasAsync();
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, System.Collections.Generic.KeyValuePair<string, string>>>> PosTaggerTip(string text) {
            return base.Channel.PosTaggerTip(text);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, System.Collections.Generic.KeyValuePair<string, string>>>>> PosTaggerTipAsync(string text) {
            return base.Channel.PosTaggerTipAsync(text);
        }
    }
}
