//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camposSemanticos.ServicioFamilias {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoPrimitiva", Namespace="http://schemas.datacontract.org/2004/07/ServicioFamiliasWCF")]
    [System.SerializableAttribute()]
    public partial class InfoPrimitiva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaPrimitivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFamiliaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSufijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimitivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RegularPrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RegularSufijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SufijoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaPalabra {
            get {
                return this.IdCategoriaPalabraField;
            }
            set {
                if ((this.IdCategoriaPalabraField.Equals(value) != true)) {
                    this.IdCategoriaPalabraField = value;
                    this.RaisePropertyChanged("IdCategoriaPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaPrimitiva {
            get {
                return this.IdCategoriaPrimitivaField;
            }
            set {
                if ((this.IdCategoriaPrimitivaField.Equals(value) != true)) {
                    this.IdCategoriaPrimitivaField = value;
                    this.RaisePropertyChanged("IdCategoriaPrimitiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFamilia {
            get {
                return this.IdFamiliaField;
            }
            set {
                if ((this.IdFamiliaField.Equals(value) != true)) {
                    this.IdFamiliaField = value;
                    this.RaisePropertyChanged("IdFamilia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrefijo {
            get {
                return this.IdPrefijoField;
            }
            set {
                if ((this.IdPrefijoField.Equals(value) != true)) {
                    this.IdPrefijoField = value;
                    this.RaisePropertyChanged("IdPrefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSufijo {
            get {
                return this.IdSufijoField;
            }
            set {
                if ((this.IdSufijoField.Equals(value) != true)) {
                    this.IdSufijoField = value;
                    this.RaisePropertyChanged("IdSufijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Primitiva {
            get {
                return this.PrimitivaField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimitivaField, value) != true)) {
                    this.PrimitivaField = value;
                    this.RaisePropertyChanged("Primitiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RegularPrefijo {
            get {
                return this.RegularPrefijoField;
            }
            set {
                if ((this.RegularPrefijoField.Equals(value) != true)) {
                    this.RegularPrefijoField = value;
                    this.RaisePropertyChanged("RegularPrefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RegularSufijo {
            get {
                return this.RegularSufijoField;
            }
            set {
                if ((this.RegularSufijoField.Equals(value) != true)) {
                    this.RegularSufijoField = value;
                    this.RaisePropertyChanged("RegularSufijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sufijo {
            get {
                return this.SufijoField;
            }
            set {
                if ((object.ReferenceEquals(this.SufijoField, value) != true)) {
                    this.SufijoField = value;
                    this.RaisePropertyChanged("Sufijo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoDerivada", Namespace="http://schemas.datacontract.org/2004/07/ServicioFamiliasWCF")]
    [System.SerializableAttribute()]
    public partial class InfoDerivada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DerivadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaDerivadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFamiliaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSufijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RegularPrefijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RegularSufijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SufijoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Derivada {
            get {
                return this.DerivadaField;
            }
            set {
                if ((object.ReferenceEquals(this.DerivadaField, value) != true)) {
                    this.DerivadaField = value;
                    this.RaisePropertyChanged("Derivada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaDerivada {
            get {
                return this.IdCategoriaDerivadaField;
            }
            set {
                if ((this.IdCategoriaDerivadaField.Equals(value) != true)) {
                    this.IdCategoriaDerivadaField = value;
                    this.RaisePropertyChanged("IdCategoriaDerivada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaPalabra {
            get {
                return this.IdCategoriaPalabraField;
            }
            set {
                if ((this.IdCategoriaPalabraField.Equals(value) != true)) {
                    this.IdCategoriaPalabraField = value;
                    this.RaisePropertyChanged("IdCategoriaPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFamilia {
            get {
                return this.IdFamiliaField;
            }
            set {
                if ((this.IdFamiliaField.Equals(value) != true)) {
                    this.IdFamiliaField = value;
                    this.RaisePropertyChanged("IdFamilia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrefijo {
            get {
                return this.IdPrefijoField;
            }
            set {
                if ((this.IdPrefijoField.Equals(value) != true)) {
                    this.IdPrefijoField = value;
                    this.RaisePropertyChanged("IdPrefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSufijo {
            get {
                return this.IdSufijoField;
            }
            set {
                if ((this.IdSufijoField.Equals(value) != true)) {
                    this.IdSufijoField = value;
                    this.RaisePropertyChanged("IdSufijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo {
            get {
                return this.PrefijoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefijoField, value) != true)) {
                    this.PrefijoField = value;
                    this.RaisePropertyChanged("Prefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RegularPrefijo {
            get {
                return this.RegularPrefijoField;
            }
            set {
                if ((this.RegularPrefijoField.Equals(value) != true)) {
                    this.RegularPrefijoField = value;
                    this.RaisePropertyChanged("RegularPrefijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RegularSufijo {
            get {
                return this.RegularSufijoField;
            }
            set {
                if ((this.RegularSufijoField.Equals(value) != true)) {
                    this.RegularSufijoField = value;
                    this.RaisePropertyChanged("RegularSufijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sufijo {
            get {
                return this.SufijoField;
            }
            set {
                if ((object.ReferenceEquals(this.SufijoField, value) != true)) {
                    this.SufijoField = value;
                    this.RaisePropertyChanged("Sufijo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFamilias.IServicioFamilias")]
    public interface IServicioFamilias {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFamilias/ConsultaPrimitivas", ReplyAction="http://tempuri.org/IServicioFamilias/ConsultaPrimitivasResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoPrimitiva> ConsultaPrimitivas(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFamilias/ConsultaPrimitivas", ReplyAction="http://tempuri.org/IServicioFamilias/ConsultaPrimitivasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoPrimitiva>> ConsultaPrimitivasAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFamilias/ConsultaDerivadas", ReplyAction="http://tempuri.org/IServicioFamilias/ConsultaDerivadasResponse")]
        System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoDerivada> ConsultaDerivadas(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFamilias/ConsultaDerivadas", ReplyAction="http://tempuri.org/IServicioFamilias/ConsultaDerivadasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoDerivada>> ConsultaDerivadasAsync(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFamilias/TieneFamilia", ReplyAction="http://tempuri.org/IServicioFamilias/TieneFamiliaResponse")]
        System.Collections.Generic.List<int> TieneFamilia(int idFormaCanonica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFamilias/TieneFamilia", ReplyAction="http://tempuri.org/IServicioFamilias/TieneFamiliaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> TieneFamiliaAsync(int idFormaCanonica);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioFamiliasChannel : camposSemanticos.ServicioFamilias.IServicioFamilias, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFamiliasClient : System.ServiceModel.ClientBase<camposSemanticos.ServicioFamilias.IServicioFamilias>, camposSemanticos.ServicioFamilias.IServicioFamilias {
        
        public ServicioFamiliasClient() {
        }
        
        public ServicioFamiliasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFamiliasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFamiliasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFamiliasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoPrimitiva> ConsultaPrimitivas(string palabra) {
            return base.Channel.ConsultaPrimitivas(palabra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoPrimitiva>> ConsultaPrimitivasAsync(string palabra) {
            return base.Channel.ConsultaPrimitivasAsync(palabra);
        }
        
        public System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoDerivada> ConsultaDerivadas(string palabra) {
            return base.Channel.ConsultaDerivadas(palabra);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<camposSemanticos.ServicioFamilias.InfoDerivada>> ConsultaDerivadasAsync(string palabra) {
            return base.Channel.ConsultaDerivadasAsync(palabra);
        }
        
        public System.Collections.Generic.List<int> TieneFamilia(int idFormaCanonica) {
            return base.Channel.TieneFamilia(idFormaCanonica);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> TieneFamiliaAsync(int idFormaCanonica) {
            return base.Channel.TieneFamiliaAsync(idFormaCanonica);
        }
    }
}
